package com.damu.xiaomi.dao;

import com.damu.xiaomi.entry.GoodsService;
import com.damu.xiaomi.entry.GoodsServiceExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface GoodsServiceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_service
     *
     * @mbg.generated Tue Dec 10 19:17:22 CST 2019
     */
    long countByExample(GoodsServiceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_service
     *
     * @mbg.generated Tue Dec 10 19:17:22 CST 2019
     */
    int deleteByExample(GoodsServiceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_service
     *
     * @mbg.generated Tue Dec 10 19:17:22 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_service
     *
     * @mbg.generated Tue Dec 10 19:17:22 CST 2019
     */
    int insert(GoodsService record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_service
     *
     * @mbg.generated Tue Dec 10 19:17:22 CST 2019
     */
    int insertSelective(GoodsService record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_service
     *
     * @mbg.generated Tue Dec 10 19:17:22 CST 2019
     */
    List<GoodsService> selectByExample(GoodsServiceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_service
     *
     * @mbg.generated Tue Dec 10 19:17:22 CST 2019
     */
    GoodsService selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_service
     *
     * @mbg.generated Tue Dec 10 19:17:22 CST 2019
     */
    int updateByExampleSelective(@Param("record") GoodsService record, @Param("example") GoodsServiceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_service
     *
     * @mbg.generated Tue Dec 10 19:17:22 CST 2019
     */
    int updateByExample(@Param("record") GoodsService record, @Param("example") GoodsServiceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_service
     *
     * @mbg.generated Tue Dec 10 19:17:22 CST 2019
     */
    int updateByPrimaryKeySelective(GoodsService record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_service
     *
     * @mbg.generated Tue Dec 10 19:17:22 CST 2019
     */
    int updateByPrimaryKey(GoodsService record);
}